/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Empresa;
import Dominio.Vaca;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Luciano
 */
public class frmListadoDeVacas extends javax.swing.JFrame {

    Empresa empresa;
    static frmListadoDeVacas instancia;
    Vaca vaca;
    private final ModeloTblVaca modeloTblVaca;
    private final ListSelectionModel lsmVacas;

    public frmListadoDeVacas(Empresa e) throws SQLException {
        initComponents();

        empresa = e;

        modeloTblVaca = new ModeloTblVaca();
        this.tblVacas.setModel(modeloTblVaca);
        this.listarVacas("idVaca");
        this.rellenarComboBox();
        lsmVacas = tblVacas.getSelectionModel();
        tblVacas.setSelectionModel(lsmVacas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnFiltrarXCaravana = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVacas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cmbFiltroVaca = new javax.swing.JComboBox<>();
        txtCaravana = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Ordenar por:");

        btnFiltrarXCaravana.setText("Buscar");
        btnFiltrarXCaravana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarXCaravanaActionPerformed(evt);
            }
        });

        tblVacas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblVacas);

        jLabel3.setText("Caravana");

        cmbFiltroVaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFiltroVaca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFiltroVacaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCaravana, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFiltrarXCaravana, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbFiltroVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(161, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCaravana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFiltrarXCaravana))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmbFiltroVaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(246, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiar() {
        this.txtCaravana.setText("");
    }

    private void listarVacas(String filtro) throws SQLException {
        modeloTblVaca.setDatos(empresa.listarVacasFiltradas(filtro));
        modeloTblVaca.fireTableDataChanged();
    }

    public static frmListadoDeVacas getInstancia(Empresa e) throws SQLException {
        if (instancia == null) {
            instancia = new frmListadoDeVacas(e);
        }
        return instancia;
    }
    private void btnFiltrarXCaravanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarXCaravanaActionPerformed
        int caravana = Integer.valueOf(this.txtCaravana.getText());

        Vaca v = empresa.buscarVacaXCaravana(caravana);

        if (v.getIdVaca() > 0) {
            frmDetalleVaca frmDV;
            try {
                frmDV = frmDetalleVaca.getInstancia(empresa, v);
                frmDV.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmInicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        limpiar();
    }//GEN-LAST:event_btnFiltrarXCaravanaActionPerformed

    private void cmbFiltroVacaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFiltroVacaItemStateChanged
        String item = evt.getItem().toString();
        String pItem;
        switch (item) {
            case "Código":
                pItem = "codigo";
                break;
            case "Raza":
                pItem = "raza";
                break;
            case "Peso":
                pItem = "peso";
                break;
            case "Edad":
                pItem = "fechaN";
                break;
            default:
                pItem = "idVaca";
                break;
        }
        try {
            listarVacas(pItem);
        } catch (SQLException ex) {
            Logger.getLogger(frmListadoDeVacas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbFiltroVacaItemStateChanged
    private void rellenarComboBox() {
        cmbFiltroVaca.removeAllItems();
        this.cmbFiltroVaca.insertItemAt("Todos", 0);
        this.cmbFiltroVaca.insertItemAt("Código", 1);
        this.cmbFiltroVaca.insertItemAt("Raza", 2);
        this.cmbFiltroVaca.insertItemAt("Peso", 3);
        this.cmbFiltroVaca.insertItemAt("Edad", 4);
        this.cmbFiltroVaca.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrarXCaravana;
    private javax.swing.JComboBox<String> cmbFiltroVaca;
    private javax.swing.JComboBox<String> cmbFiltros;
    private javax.swing.JComboBox<String> cmbFiltros1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVacas;
    private javax.swing.JTextField txtCaravana;
    // End of variables declaration//GEN-END:variables
}
